### PR TITLE
Add linters to project

### PR DESCRIPTION
**Pull request by alanluqman**
In this pull Request, I added these files (index.html , style.css , linters.yml , .gitignore , MIT.md , README.md and test.md)
- index.html  is the home page of the website.
- style.css  is some formatting stuffs like color and text alignment.
- .gitignore for ignoring some file and specific extensions.
- MIT.md is the License file.
- README.md is a summary about the website.
- test.md is a file which ignored by git .

### CODE REVIEW

**Review by tresorsawasawa — COMMENTED** [review]
# STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @alanluqman 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly use the hello-microverse project for requesting the review. As you can see you requested from **setup and mobile project**. You can check today's project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

---
Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

---
_Invalid Code Review Request **Does not count** into the code reviews limit._

**Review by phelian23 — CHANGES_REQUESTED** [review]
Hi @alanluqman, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights


## Required Changes ♻️

- [x] The linters file is not set up correctly. Kindly follow the instructions [here](https://github.com/microverseinc/linters-config) to set up the linters correctly, and make sure that all are passing.

- [x]  Please use [this template](https://github.com/microverseinc/readme-template) to make you README.md file descriptive, but remember to customize it to your project.
- [x] Kindly add some description to the pull request, summarizing what changes made in the pull request.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by ShahierNashaat — CHANGES_REQUESTED** [review]
Hi <STUDENT_MENTION>, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] Kindly be noticed that the README file should be descriptive? AKA: Microverse README template should be used.
- [x] Kindly be noticed that the Pull Request should have a summary describing introduced changes in more detail.
- [x] Kindly be noticed that the .gitignore file should be listing `test.md` file and `node_modules`.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by alanluqman** [comment]
### **Add Linter for Stylizing code .**
**A Linter is a tool that analyzes your source code to flag programming errors, bugs, stylistic errors, This tool adds an action to the Repository and check a bunch of concepts like  :**  
* Lighthouse
* Webhint
* Stylelint
* Node_modules checker

**Review by Kandy-Peter — APPROVED** [review]
## HELLO @alanluqman   👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉, 

Cheers and Happy coding!👏👏👏



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Pull request merged**
